# Generated by Django 5.2.13 on 2026-04-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='menu_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='menu_product',
        ),
        migrations.AlterModelTable(
            name='productoption',
            table='menu_productoption',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('aggregate_type', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'menu_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='menu_event_type_75fd4a_idx'), models.Index(fields=['aggregate_id'], name='menu_event_aggrega_57ba39_idx'), models.Index(fields=['created_at'], name='menu_event_created_a034b9_idx')],
            },
        ),
    ]
