services:
  db-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "15432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-menu:
    image: postgres:15
    environment:
      POSTGRES_DB: menu_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
    volumes:
      - postgres_menu_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d menu_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-orders:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5434:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-payments:
    image: postgres:15
    environment:
      POSTGRES_DB: payments_billing_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5435:5432"
    volumes:
      - postgres_payments_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d payments_billing_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-reports:
    image: postgres:15
    environment:
      POSTGRES_DB: reports_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5436:5432"
    volumes:
      - postgres_reports_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reports_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  auth:
    build:
      context: ./backend/auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/auth_service:/app
      - ./backend/shared:/shared
      - auth_media:/app/media
    environment:
      - DATABASE_HOST=db-auth
      - DATABASE_PORT=5432
      - DATABASE_NAME=auth_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - PYTHONPATH=/app:/shared
    depends_on:
      db-auth:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always

  menu:
    build:
      context: ./backend/menu_service
    ports:
      - "8001:8000"
    volumes:
      - ./backend/menu_service:/app
      - ./backend/shared:/shared
      - menu_media:/app/media
    environment:
      - DATABASE_HOST=db-menu
      - DATABASE_PORT=5432
      - DATABASE_NAME=menu_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_EXCHANGE=events
      - PYTHONPATH=/app:/shared
    depends_on:
      db-menu:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always

  celery:
    build:
      context: ./backend/auth_service
    volumes:
      - ./backend/auth_service:/app
      - ./backend/shared:/shared
    environment:
      - DATABASE_HOST=db-auth
      - DATABASE_PORT=5432
      - DATABASE_NAME=auth_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - PYTHONPATH=/app:/shared
    command: celery -A auth_project worker -l info
    depends_on:
      db-auth:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  orders:
    build:
      context: ./backend/orders_services/msvc-orders_services
    ports:
      - "8002:8002"
    volumes:
      - ./backend/orders_services/msvc-orders_services:/app
      - maven_cache:/root/.m2
    environment:
      - DATABASE_HOST=db-orders
      - DATABASE_PORT=5432
      - DATABASE_NAME=orders_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_EXCHANGE=events
      - RABBITMQ_PAYMENT_CONFIRMED_QUEUE=orders.payment-confirmed
      - JWT_SECRET=django-insecure-xgp=59ff8*(y8*@k-wpr@lpsh(pxt)h9fxsew5)pa3cke0@e)z
    depends_on:
      db-orders:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always

  payments-billing:
    build:
      context: ./backend/payments_billing_service/msvc-payments-billing-service
    ports:
      - "8003:8003"
    volumes:
      - ./backend/payments_billing_service/msvc-payments-billing-service:/app
      - maven_cache:/root/.m2
    environment:
      - DATABASE_HOST=db-payments
      - DATABASE_PORT=5432
      - DATABASE_NAME=payments_billing_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_EXCHANGE=events
      - JWT_SECRET=django-insecure-xgp=59ff8*(y8*@k-wpr@lpsh(pxt)h9fxsew5)pa3cke0@e)z
      - RABBITMQ_PAYMENT_CONFIRMED_QUEUE=orders.payment-confirmed
    depends_on:
      db-payments:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always

  reports:
    build:
      context: ./backend/reports_service/msvc-reports_service
    ports:
      - "8004:8004"
    volumes:
      - ./backend/reports_service/msvc-reports_service:/app
      - maven_cache:/root/.m2
    environment:
      - DATABASE_HOST=db-reports
      - DATABASE_PORT=5432
      - DATABASE_NAME=reports_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_EXCHANGE=events
      - RABBITMQ_REPORTS_PAYMENT_CONFIRMED_QUEUE=reports.payment-confirmed
    depends_on:
      db-reports:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always

  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./backend/api-gateway:/app
      - maven_cache:/root/.m2
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_ENABLED=false
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - AUTH_SERVICE_URI=http://auth:8000
      - MENU_SERVICE_URI=http://menu:8000
      - ORDERS_SERVICE_URI=http://orders:8002
      - PAYMENTS_SERVICE_URI=http://payments-billing:8003
      - REPORTS_SERVICE_URI=http://reports:8004
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      - auth
      - menu
      - orders
      - payments-billing
      - reports
    restart: always
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - auth
      - menu
      - orders
      - payments-billing
      - reports
      - api-gateway
    restart: always

volumes:
  postgres_auth_data:
  postgres_menu_data:
  postgres_orders_data:
  postgres_payments_data:
  postgres_reports_data:
  rabbitmq_data:
  redis_data:
  auth_media:
  menu_media:
  maven_cache:
  frontend_node_modules:
