services:
  db-write:
    image: postgres:15
    environment:
      POSTGRES_DB: menu_db_write
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_write_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d menu_db_write"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-read:
    image: postgres:15
    environment:
      POSTGRES_DB: menu_db_read
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
    volumes:
      - postgres_read_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d menu_db_read"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  auth:
    image: python:3.11
    ports:
      - "8000:8000" # Cambiado de 8001 a 8000
    volumes:
      - ./auth_service:/app
      - ./shared:/shared # Agregar shared
    working_dir: /app
    environment:
      - DATABASE_HOST=db-write
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - PYTHONPATH=/app:/shared # Agregar shared al path
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db-write:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always

  menu:
    image: python:3.11
    ports:
      - "8001:8000" # Cambiado de 8002 a 8001
    volumes:
      - ./menu_service:/app
      - ./shared:/shared # Agregar shared
      - menu_media:/app/media
    working_dir: /app
    environment:
      - PYTHONPATH=/app:/shared # Agregar shared al path
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db-write:
        condition: service_healthy
    restart: always

  celery:
    image: python:3.11
    volumes:
      - ./auth_service:/app
      - ./shared:/shared
    working_dir: /app
    environment:
      - DATABASE_HOST=db-write
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - PYTHONPATH=/app:/shared
    command: sh -c "pip install -r requirements.txt && celery -A auth_project worker -l info"
    depends_on:
      db-write:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    restart: always

volumes:
  postgres_write_data:
  postgres_read_data:
  rabbitmq_data:
  redis_data:
  menu_media:
