# Generated by Django 5.2.13 on 2026-05-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
