# Generated by Django 5.2.13 on 2026-04-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event'),
    ]

    operations = [
        # Agregar campos para Event Sourcing completo
        migrations.AddField(
            model_name='event',
            name='aggregate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='aggregate_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]