# Generated by Django 5.2.13 on 2026-06-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_restaurant_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='userrestaurant',
            options={'verbose_name': 'Asignación usuario-restaurante', 'verbose_name_plural': 'Asignaciones usuario-restaurante'},
        ),
        migrations.AlterUniqueTogether(
            name='userrestaurant',
            unique_together={('user', 'restaurant')},
        ),
        migrations.AlterModelTable(
            name='event',
            table='users_event',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='users_restaurant',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
        migrations.AlterModelTable(
            name='userrestaurant',
            table='users_user_restaurant',
        ),
    ]
