# Generated by Django 5.2.13 on 2026-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_event_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Super Administrador'), ('restaurante', 'Administrador de Restaurante'), ('empleado', 'Empleado')], default='cliente', max_length=20),
        ),
    ]
