# Generated by Django 5.2.13 on 2026-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_restaurant_lat_restaurant_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Super Administrador'), ('restaurante', 'Administrador de Restaurante'), ('empleado', 'Empleado'), ('repartidor', 'Repartidor')], default='cliente', max_length=20),
        ),
    ]
