spring.application.name=msvc-reports_service
server.port=8004

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5436}/${DATABASE_NAME:reports_db}
spring.datasource.username=${DATABASE_USER:admin}
spring.datasource.password=${DATABASE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

reports.events.exchange=${RABBITMQ_EXCHANGE:events}
reports.events.payment-confirmed.queue=${RABBITMQ_REPORTS_PAYMENT_CONFIRMED_QUEUE:reports.payment-confirmed}

reports.security.jwt.secret=${JWT_SECRET:django-insecure-xgp=59ff8*(y8*@k-wpr@lpsh(pxt)h9fxsew5)pa3cke0@e)z}
